//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biofarma.Service.ERP.AssetERP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonAsUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SCC_WSAssetObj", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class SCC_WSAssetObj : Biofarma.Service.ERP.AssetERP.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AcquisitionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetGroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CostCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NetBookValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomorInventarisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TanggalPerolehanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AcquisitionDate {
            get {
                return this.AcquisitionDateField;
            }
            set {
                if ((this.AcquisitionDateField.Equals(value) != true)) {
                    this.AcquisitionDateField = value;
                    this.RaisePropertyChanged("AcquisitionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetGroupID {
            get {
                return this.AssetGroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetGroupIDField, value) != true)) {
                    this.AssetGroupIDField = value;
                    this.RaisePropertyChanged("AssetGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetGroupName {
            get {
                return this.AssetGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetGroupNameField, value) != true)) {
                    this.AssetGroupNameField = value;
                    this.RaisePropertyChanged("AssetGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetID {
            get {
                return this.AssetIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetIDField, value) != true)) {
                    this.AssetIDField = value;
                    this.RaisePropertyChanged("AssetID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetName {
            get {
                return this.AssetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetNameField, value) != true)) {
                    this.AssetNameField = value;
                    this.RaisePropertyChanged("AssetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostCenter {
            get {
                return this.CostCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.CostCenterField, value) != true)) {
                    this.CostCenterField = value;
                    this.RaisePropertyChanged("CostCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorType {
            get {
                return this.MajorTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorTypeField, value) != true)) {
                    this.MajorTypeField = value;
                    this.RaisePropertyChanged("MajorType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MajorTypeName {
            get {
                return this.MajorTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorTypeNameField, value) != true)) {
                    this.MajorTypeNameField = value;
                    this.RaisePropertyChanged("MajorTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NetBookValue {
            get {
                return this.NetBookValueField;
            }
            set {
                if ((this.NetBookValueField.Equals(value) != true)) {
                    this.NetBookValueField = value;
                    this.RaisePropertyChanged("NetBookValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomorInventaris {
            get {
                return this.NomorInventarisField;
            }
            set {
                if ((object.ReferenceEquals(this.NomorInventarisField, value) != true)) {
                    this.NomorInventarisField = value;
                    this.RaisePropertyChanged("NomorInventaris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TanggalPerolehan {
            get {
                return this.TanggalPerolehanField;
            }
            set {
                if ((this.TanggalPerolehanField.Equals(value) != true)) {
                    this.TanggalPerolehanField = value;
                    this.RaisePropertyChanged("TanggalPerolehan");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj))]
    public partial class XppObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Biofarma.Service.ERP.AssetERP.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Biofarma.Service.ERP.AssetERP.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Biofarma.Service.ERP.AssetERP.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Biofarma.Service.ERP.AssetERP.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Biofarma.Service.ERP.AssetERP.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Biofarma.Service.ERP.AssetERP.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Biofarma.Service.ERP.AssetERP.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Biofarma.Service.ERP.AssetERP.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/netfx/2009/05/routing", ConfigurationName="AssetERP.IRequestReplyRouter")]
    public interface IRequestReplyRouter {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestReplyRouterChannel : Biofarma.Service.ERP.AssetERP.IRequestReplyRouter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestReplyRouterClient : System.ServiceModel.ClientBase<Biofarma.Service.ERP.AssetERP.IRequestReplyRouter>, Biofarma.Service.ERP.AssetERP.IRequestReplyRouter {
        
        public RequestReplyRouterClient() {
        }
        
        public RequestReplyRouterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestReplyRouterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestReplyRouterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestReplyRouterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="AssetERP.SCC_WSAssetService")]
    public interface SCC_WSAssetService {
        
        // CODEGEN: Generating message contract since the wrapper name (SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest) of message SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest does not match the default value (getAssetDetailByNoInventaris)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCC_WSAssetService/getAssetDetailByNoInventaris", ReplyAction="http://tempuri.org/SCC_WSAssetService/getAssetDetailByNoInventarisResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Biofarma.Service.ERP.AssetERP.AifFault), Action="http://tempuri.org/SCC_WSAssetService/getAssetDetailByNoInventarisAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByNoInventarisResponse getAssetDetailByNoInventaris(Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SCC_WSAssetServiceGetAllAssetRequest) of message SCC_WSAssetServiceGetAllAssetRequest does not match the default value (getAllAsset)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCC_WSAssetService/getAllAsset", ReplyAction="http://tempuri.org/SCC_WSAssetService/getAllAssetResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Biofarma.Service.ERP.AssetERP.AifFault), Action="http://tempuri.org/SCC_WSAssetService/getAllAssetAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAllAssetResponse getAllAsset(Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAllAssetRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SCC_WSAssetServiceGetAssetDetailRequest) of message SCC_WSAssetServiceGetAssetDetailRequest does not match the default value (getAssetDetail)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCC_WSAssetService/getAssetDetail", ReplyAction="http://tempuri.org/SCC_WSAssetService/getAssetDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Biofarma.Service.ERP.AssetERP.AifFault), Action="http://tempuri.org/SCC_WSAssetService/getAssetDetailAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailResponse getAssetDetail(Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest) of message SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest does not match the default value (getAssetDetailByAssetCode)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SCC_WSAssetService/getAssetDetailByAssetCode", ReplyAction="http://tempuri.org/SCC_WSAssetService/getAssetDetailByAssetCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Biofarma.Service.ERP.AssetERP.AifFault), Action="http://tempuri.org/SCC_WSAssetService/getAssetDetailByAssetCodeAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByAssetCodeResponse getAssetDetailByAssetCode(Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public Biofarma.Service.ERP.AssetERP.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _noInventaris;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime fromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public System.DateTime toDate;
        
        public SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest() {
        }
        
        public SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest(Biofarma.Service.ERP.AssetERP.CallContext CallContext, string _noInventaris, System.DateTime fromDate, System.DateTime toDate) {
            this.CallContext = CallContext;
            this._noInventaris = _noInventaris;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCC_WSAssetServiceGetAssetDetailByNoInventarisResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SCC_WSAssetServiceGetAssetDetailByNoInventarisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] response;
        
        public SCC_WSAssetServiceGetAssetDetailByNoInventarisResponse() {
        }
        
        public SCC_WSAssetServiceGetAssetDetailByNoInventarisResponse(Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCC_WSAssetServiceGetAllAssetRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SCC_WSAssetServiceGetAllAssetRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public Biofarma.Service.ERP.AssetERP.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public System.DateTime fromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime toDate;
        
        public SCC_WSAssetServiceGetAllAssetRequest() {
        }
        
        public SCC_WSAssetServiceGetAllAssetRequest(Biofarma.Service.ERP.AssetERP.CallContext CallContext, System.DateTime fromDate, System.DateTime toDate) {
            this.CallContext = CallContext;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCC_WSAssetServiceGetAllAssetResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SCC_WSAssetServiceGetAllAssetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] response;
        
        public SCC_WSAssetServiceGetAllAssetResponse() {
        }
        
        public SCC_WSAssetServiceGetAllAssetResponse(Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCC_WSAssetServiceGetAssetDetailRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SCC_WSAssetServiceGetAssetDetailRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public Biofarma.Service.ERP.AssetERP.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _majorType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _groupID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public string _costCenter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public System.DateTime fromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=4)]
        public System.DateTime toDate;
        
        public SCC_WSAssetServiceGetAssetDetailRequest() {
        }
        
        public SCC_WSAssetServiceGetAssetDetailRequest(Biofarma.Service.ERP.AssetERP.CallContext CallContext, string _majorType, string _groupID, string _costCenter, System.DateTime fromDate, System.DateTime toDate) {
            this.CallContext = CallContext;
            this._majorType = _majorType;
            this._groupID = _groupID;
            this._costCenter = _costCenter;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCC_WSAssetServiceGetAssetDetailResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SCC_WSAssetServiceGetAssetDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] response;
        
        public SCC_WSAssetServiceGetAssetDetailResponse() {
        }
        
        public SCC_WSAssetServiceGetAssetDetailResponse(Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public Biofarma.Service.ERP.AssetERP.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _assetID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public System.DateTime fromDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public System.DateTime toDate;
        
        public SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest() {
        }
        
        public SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest(Biofarma.Service.ERP.AssetERP.CallContext CallContext, string _assetID, System.DateTime fromDate, System.DateTime toDate) {
            this.CallContext = CallContext;
            this._assetID = _assetID;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SCC_WSAssetServiceGetAssetDetailByAssetCodeResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class SCC_WSAssetServiceGetAssetDetailByAssetCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] response;
        
        public SCC_WSAssetServiceGetAssetDetailByAssetCodeResponse() {
        }
        
        public SCC_WSAssetServiceGetAssetDetailByAssetCodeResponse(Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SCC_WSAssetServiceChannel : Biofarma.Service.ERP.AssetERP.SCC_WSAssetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCC_WSAssetServiceClient : System.ServiceModel.ClientBase<Biofarma.Service.ERP.AssetERP.SCC_WSAssetService>, Biofarma.Service.ERP.AssetERP.SCC_WSAssetService {
        
        public SCC_WSAssetServiceClient() {
        }
        
        public SCC_WSAssetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCC_WSAssetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCC_WSAssetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCC_WSAssetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByNoInventarisResponse Biofarma.Service.ERP.AssetERP.SCC_WSAssetService.getAssetDetailByNoInventaris(Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest request) {
            return base.Channel.getAssetDetailByNoInventaris(request);
        }
        
        public Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] getAssetDetailByNoInventaris(Biofarma.Service.ERP.AssetERP.CallContext CallContext, string _noInventaris, System.DateTime fromDate, System.DateTime toDate) {
            Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest inValue = new Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByNoInventarisRequest();
            inValue.CallContext = CallContext;
            inValue._noInventaris = _noInventaris;
            inValue.fromDate = fromDate;
            inValue.toDate = toDate;
            Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByNoInventarisResponse retVal = ((Biofarma.Service.ERP.AssetERP.SCC_WSAssetService)(this)).getAssetDetailByNoInventaris(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAllAssetResponse Biofarma.Service.ERP.AssetERP.SCC_WSAssetService.getAllAsset(Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAllAssetRequest request) {
            return base.Channel.getAllAsset(request);
        }
        
        public Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] getAllAsset(Biofarma.Service.ERP.AssetERP.CallContext CallContext, System.DateTime fromDate, System.DateTime toDate) {
            Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAllAssetRequest inValue = new Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAllAssetRequest();
            inValue.CallContext = CallContext;
            inValue.fromDate = fromDate;
            inValue.toDate = toDate;
            Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAllAssetResponse retVal = ((Biofarma.Service.ERP.AssetERP.SCC_WSAssetService)(this)).getAllAsset(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailResponse Biofarma.Service.ERP.AssetERP.SCC_WSAssetService.getAssetDetail(Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailRequest request) {
            return base.Channel.getAssetDetail(request);
        }
        
        public Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] getAssetDetail(Biofarma.Service.ERP.AssetERP.CallContext CallContext, string _majorType, string _groupID, string _costCenter, System.DateTime fromDate, System.DateTime toDate) {
            Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailRequest inValue = new Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailRequest();
            inValue.CallContext = CallContext;
            inValue._majorType = _majorType;
            inValue._groupID = _groupID;
            inValue._costCenter = _costCenter;
            inValue.fromDate = fromDate;
            inValue.toDate = toDate;
            Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailResponse retVal = ((Biofarma.Service.ERP.AssetERP.SCC_WSAssetService)(this)).getAssetDetail(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByAssetCodeResponse Biofarma.Service.ERP.AssetERP.SCC_WSAssetService.getAssetDetailByAssetCode(Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest request) {
            return base.Channel.getAssetDetailByAssetCode(request);
        }
        
        public Biofarma.Service.ERP.AssetERP.SCC_WSAssetObj[] getAssetDetailByAssetCode(Biofarma.Service.ERP.AssetERP.CallContext CallContext, string _assetID, System.DateTime fromDate, System.DateTime toDate) {
            Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest inValue = new Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByAssetCodeRequest();
            inValue.CallContext = CallContext;
            inValue._assetID = _assetID;
            inValue.fromDate = fromDate;
            inValue.toDate = toDate;
            Biofarma.Service.ERP.AssetERP.SCC_WSAssetServiceGetAssetDetailByAssetCodeResponse retVal = ((Biofarma.Service.ERP.AssetERP.SCC_WSAssetService)(this)).getAssetDetailByAssetCode(inValue);
            return retVal.response;
        }
    }
}
